### ISSUE TITLE
Twig 3.0 support

### ISSUE THREAD

**Issue by QuentinNanomonx** [roukmoute/HashidsBundle#10]
Hello,
Thanks for your bundle, great work !
Twig have a new version and change it's way to deal with extensions: 
![image](https://user-images.githubusercontent.com/46820049/69752999-836ff680-1120-11ea-93f4-a811eceb22e0.png)
Is it possible to change your src\Twig\HashidsExtension.php by this to make it works ? :

```
<?php

declare(strict_types = 1);

namespace Roukmoute\HashidsBundle\Twig;

use Roukmoute\HashidsBundle\Hashids;
use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;

class HashidsExtension extends AbstractExtension
{
    /**
     * @var Hashids
     */
    private $hashids;

    public function __construct(Hashids $hashids)
    {
        $this->hashids = $hashids;
    }

    public function getFilters(): array
    {
        return [
            new TwigFilter('hashids_encode', [$this, 'encode']),
            new TwigFilter('hashids_decode', [$this, 'decode']),
        ];
    }

    public function encode($number): string
    {
        return $this->hashids->encode($number);
    }

    public function decode($hash): array
    {
        return $this->hashids->decode($hash);
    }
}
```
(regarding to https://symfony.com/doc/4.0/templating/twig_extension.html it's supported from SF4.0 so it's should be fine for everyone)
Thanks in advance :)

**Comment by roukmoute** [comment]
Hey thanks for your support.  
You are right, I will fix that quickly or do not hesitate to create a P.R. of course!
